package com.mycompany.views;

import java.awt.Color;
import OP.DAOAutobusesimpl;
import OP.DAOConductoresimpl;
import OP.DAOReporteimpl;
import com.mycompany.interfaces.DAOAutobuses;
import com.mycompany.interfaces.DAOConductores;
import com.mycompany.interfaces.DAOReporte;
import Utils.Utils;

public class RegistrarS extends javax.swing.JPanel {

    /**
     * Creates new form RegistrarE
     */
    public RegistrarS() {
        initComponents();
        InitStyles();
    }

    private void InitStyles() {
        title.putClientProperty("FlatLaf.style", "font: bold $h3.regular.font");
        title.setForeground(Color.black);
        regS.setForeground(Color.white);
        regS.putClientProperty("FlatLaf.style", "font:14 $semibold.font");
        idcond.putClientProperty("FlatLaf.styleClass", "large");
        idcond.setForeground(Color.black);
        idaut.putClientProperty("FlatLaf.styleClass", "large");
        idaut.setForeground(Color.black);
        idconTxt.putClientProperty("JTextField.placeholderText", "Ingrese el ID del conductor");
        idautTxt.putClientProperty("JTextField.placeholderText", "Ingrese el ID del autobus");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        idcond = new javax.swing.JLabel();
        regS = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        idautTxt = new javax.swing.JTextField();
        idaut = new javax.swing.JLabel();
        idconTxt = new javax.swing.JTextField();
        title = new javax.swing.JLabel();

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setPreferredSize(new java.awt.Dimension(576, 410));

        idcond.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        idcond.setText("ID Conductor");

        regS.setBackground(new java.awt.Color(0, 102, 153));
        regS.setText("Registrar Salida");
        regS.setBorderPainted(false);
        regS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        regS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regSActionPerformed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        idautTxt.setBackground(new java.awt.Color(255, 255, 255));

        idaut.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        idaut.setText("ID Autobus");

        idconTxt.setBackground(new java.awt.Color(255, 255, 255));
        idconTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idconTxtActionPerformed(evt);
            }
        });

        title.setText("Registrar Salida");

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(title))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idcond, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idconTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(38, 38, 38)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idaut, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idautTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                .addComponent(regS, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(201, 201, 201))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(title)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addComponent(idcond)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(idconTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(bgLayout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addComponent(idaut)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(idautTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(regS, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 576, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void regSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regSActionPerformed

        String id_cond = idconTxt.getText();
        String id_aut = idautTxt.getText();

        // Validaciones para los campos
        if (id_cond.isEmpty() || id_aut.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Debe llenar todos los campos. \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
            if (id_cond.isEmpty()) {
                idconTxt.requestFocus();
            } else {
                idautTxt.requestFocus();
            }
            return;
        } else if (!Utils.isNumeric(id_cond) || !Utils.isNumeric(id_aut)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Los campos ID conductor y el ID del autobus deben ser números enteros. \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
            idconTxt.requestFocus();
            return;
        } else if (Integer.parseInt(id_cond) <= 0 || Integer.parseInt(id_aut) <= 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Los campos ID conductor y el ID del autobus deben ser mayor que 0. \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
            idconTxt.requestFocus();
            return;
        }

        try {
            DAOConductores daoConductores = new DAOConductoresimpl();

            // Validamos existencia del conductor
            com.mycompany.models.Conductores currentConductor = daoConductores.getConductorById(Integer.parseInt(id_cond));
            if (currentConductor == null) {
                javax.swing.JOptionPane.showMessageDialog(this, "No se encontró ningún conductor con ese ID. \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
                idconTxt.requestFocus();
                return;
            }

            DAOAutobuses daoAutobuses = new DAOAutobusesimpl();

            // Validamos existencia del autobús
            com.mycompany.models.Autobuses currentAutobus = daoAutobuses.getAutobusById(Integer.parseInt(id_aut));
            if (currentAutobus == null) {
                javax.swing.JOptionPane.showMessageDialog(this, "No se encontró ningún autobus con ese ID. \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
                idautTxt.requestFocus();
                return;
            }

            DAOReporte daoReporte = new DAOReporteimpl();

            // Validamos que el conductor no tenga ya un autobús asignado.
            com.mycompany.models.Reporte currentAssignment = daoReporte.getReporte(currentConductor, currentAutobus);
            if (currentAssignment != null) {
                javax.swing.JOptionPane.showMessageDialog(this, "Este conductor ya tiene asignado este autobús en esta ruta. \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
                idautTxt.requestFocus();
                return;
            }
            if (currentConductor != null && currentAutobus != null) {
                // Todo OK: Registrar salida del autobús con el conductor.
                String fechaActual = Utils.getFechaActual();
                com.mycompany.models.Reporte reporte = new com.mycompany.models.Reporte();
                reporte.setCond_id(currentConductor.getId());
                reporte.setAut_id(currentAutobus.getID());
                reporte.setDate_out(fechaActual);
                daoReporte.registrar(reporte);

                javax.swing.JOptionPane.showMessageDialog(this, "Autobús ID: " + currentAutobus.getID() + " conducido por " + currentConductor.getNombres() + " registrado exitosamente.\n", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                idconTxt.setText("");
                idautTxt.setText("");
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Error: No se puede registrar la salida. Conductor o autobús no encontrado.\n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Ocurrió un error al registrar la salida del autobús. \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
            e.printStackTrace(); // Imprimir la excepción en la consola

        }

    }//GEN-LAST:event_regSActionPerformed

    private void idconTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idconTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idconTxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JLabel idaut;
    private javax.swing.JTextField idautTxt;
    private javax.swing.JTextField idconTxt;
    private javax.swing.JLabel idcond;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton regS;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
