package com.mycompany.views;

import java.awt.Color;
import OP.DAOAutobusesimpl;
import OP.DAOConductoresimpl;
import OP.DAOReporteimpl;
import com.mycompany.interfaces.DAOAutobuses;
import com.mycompany.interfaces.DAOConductores;
import com.mycompany.interfaces.DAOReporte;
import Utils.Utils;

public class RegistrarE extends javax.swing.JPanel {

    /**
     * Creates new form RegistrarE
     */
    public RegistrarE() {
        initComponents();
        InitStyles();
    }

    private void InitStyles() {
        title.putClientProperty("FlatLaf.style", "font: bold $h3.regular.font");
        title.setForeground(Color.black);
        regE.setForeground(Color.white);
        regE.putClientProperty("FlatLaf.style", "font:14 $semibold.font");
        idcond.putClientProperty("FlatLaf.styleClass", "large");
        idcond.setForeground(Color.black);
        idaut.putClientProperty("FlatLaf.styleClass", "large");
        idaut.setForeground(Color.black);
        idcondTxt.putClientProperty("JTextField.placeholderText", "Ingrese el ID del conductor");
        idautTxt.putClientProperty("JTextField.placeholderText", "Ingrese el ID del autobus");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        idcond = new javax.swing.JLabel();
        idautTxt = new javax.swing.JTextField();
        idaut = new javax.swing.JLabel();
        regE = new javax.swing.JButton();
        idcondTxt = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        title = new javax.swing.JLabel();

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setPreferredSize(new java.awt.Dimension(576, 410));

        idcond.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        idcond.setText("ID Conductor");

        idautTxt.setBackground(new java.awt.Color(255, 255, 255));

        idaut.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        idaut.setText("ID Autobus");

        regE.setBackground(new java.awt.Color(0, 102, 153));
        regE.setText("Registrar Entrada");
        regE.setBorderPainted(false);
        regE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        regE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regEActionPerformed(evt);
            }
        });

        idcondTxt.setBackground(new java.awt.Color(255, 255, 255));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        title.setText("Registrar Entrada");

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idcondTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idcond))
                        .addGap(39, 39, 39)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(idaut))
                            .addGroup(bgLayout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(idautTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(title)))
                .addGap(34, 34, 34))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                .addComponent(regE, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(197, 197, 197))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(title)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addComponent(idcond)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(idcondTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(bgLayout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addComponent(idaut)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(idautTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(regE, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void regEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regEActionPerformed
        String id_cond = idcondTxt.getText();
        String id_aut = idautTxt.getText();

// Validaciones para los campos
        if (id_cond.isEmpty() || id_aut.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Debe llenar todos los campos. \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
            if (id_cond.isEmpty()) {
                idcondTxt.requestFocus();
            } else {
                idautTxt.requestFocus();
            }
            return;
        } else if (!Utils.isNumeric(id_cond) || !Utils.isNumeric(id_aut)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Los campos ID conductor y ID del autobus deben ser números enteros. \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
            idcondTxt.requestFocus();
            return;
        } else if (Integer.parseInt(id_cond) <= 0 || Integer.parseInt(id_aut) <= 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Los campos ID conductor y ID del autobus deben ser mayores que 0. \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
            idcondTxt.requestFocus();
            return;
        }

        try {
            DAOConductores daoConductores = new DAOConductoresimpl();

            // Validamos existencia del conductor
            com.mycompany.models.Conductores currentConductor = daoConductores.getConductorById(Integer.parseInt(id_cond));
            if (currentConductor == null) {
                javax.swing.JOptionPane.showMessageDialog(this, "No se encontró ningún conductor con ese ID. \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
                idcondTxt.requestFocus();
                return;
            }

            DAOAutobuses daoAutobuses = new DAOAutobusesimpl();

            // Validamos existencia del autobús
            com.mycompany.models.Autobuses currentAutobus = daoAutobuses.getAutobusById(Integer.parseInt(id_aut));
            if (currentAutobus == null) {
                javax.swing.JOptionPane.showMessageDialog(this, "No se encontró ningún autobús con ese ID. \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
                idautTxt.requestFocus();
                return;
            }

            DAOReporte daoReporte = new DAOReporteimpl();

            // Validamos que el conductor no tenga ya un autobús asignado.
            com.mycompany.models.Reporte currentReporte = daoReporte.getReporte(currentConductor, currentAutobus);
            if (currentReporte == null) {
                javax.swing.JOptionPane.showMessageDialog(this, "No se ha podido encontrar el préstamo correspiendote a los datos ingresados. \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
                idautTxt.requestFocus();
                return;
            }
            currentReporte.setDate_return(Utils.getFechaActual());
            daoReporte.modificar(currentReporte);

            javax.swing.JOptionPane.showMessageDialog(this, "Autobús ID: " + currentAutobus.getID() + " conducido por " + currentConductor.getNombres() + " registrado exitosamente.\n", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            idcondTxt.setText("");
            idautTxt.setText("");
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Ocurrió un error al registrar la entrada del autobús. \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
            e.printStackTrace(); // Imprimir la excepción en la consola
        }
    }//GEN-LAST:event_regEActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JLabel idaut;
    private javax.swing.JTextField idautTxt;
    private javax.swing.JLabel idcond;
    private javax.swing.JTextField idcondTxt;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton regE;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
