package com.mycompany.views;

import OP.DAOAutobusesimpl;
import com.mycompany.interfaces.DAOAutobuses;
import java.awt.Color;

public class RegistrarAut extends javax.swing.JPanel {

    boolean isEdition = false;
    com.mycompany.models.Autobuses autobusEdition;

    public RegistrarAut() {
        initComponents();
        InitStyles();
    }

    public RegistrarAut(com.mycompany.models.Autobuses autobus) {
        initComponents();
        isEdition = true;
        autobusEdition = autobus;
        InitStyles();
    }

    private void InitStyles() {
        title.putClientProperty("FlatLaf.style", "font: bold $h3.regular.font");
        title.setForeground(Color.black);
        marcaTxt.putClientProperty("JTextField.placeholderText", "Ingrese la marca del autobus.");
        modeloTxt.putClientProperty("JTextField.placeholderText", "Ingrese el modelo del autobus.");
        añofabTxt.putClientProperty("JTextField.placeholderText", "Ingrese el año de fabricacion del autobus.");
        plazas_dispTxt.putClientProperty("JTextField.placeholderText", "Ingrese las plazas disponibles.");
        placaTxt.putClientProperty("JTextField.placeholderText", "Ingrese la placa del autobus.");
        kilomeTxt.putClientProperty("JTextField.placeholderText", "Ingrese el kilometraje del autobus.");
        rutaTxt.putClientProperty("JTextField.placeholderText", "Ingrese la ruta del autobus.");

        if (isEdition) {
            title.setText("Editar autobus");
            button.setText("Guardar");

            if (autobusEdition != null) {
                marcaTxt.setText(autobusEdition.getMarca());
                modeloTxt.setText(autobusEdition.getModelo());
                añofabTxt.setText(autobusEdition.getAño_fabricacion());
                plazas_dispTxt.setText(String.valueOf(autobusEdition.getPlazas_disponibles()));
                placaTxt.setText(autobusEdition.getPlaca());
                kilomeTxt.setText(String.valueOf(autobusEdition.getKilometraje()));
                rutaTxt.setText(String.valueOf(autobusEdition.getRuta()));
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        marca = new javax.swing.JLabel();
        rutaTxt = new javax.swing.JTextField();
        ruta = new javax.swing.JLabel();
        modeloTxt = new javax.swing.JTextField();
        año_fab = new javax.swing.JLabel();
        añofabTxt = new javax.swing.JTextField();
        plazas_disp = new javax.swing.JLabel();
        plazas_dispTxt = new javax.swing.JTextField();
        placa = new javax.swing.JLabel();
        placaTxt = new javax.swing.JTextField();
        kilome = new javax.swing.JLabel();
        kilomeTxt = new javax.swing.JTextField();
        button = new javax.swing.JButton();
        marcaTxt = new javax.swing.JTextField();
        modelo1 = new javax.swing.JLabel();

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setPreferredSize(new java.awt.Dimension(576, 410));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setText("Registrar nuevo autobus");
        bg.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, 373, -1));

        marca.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        marca.setText("Marca");
        bg.add(marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 208, -1));

        rutaTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rutaTxtActionPerformed(evt);
            }
        });
        bg.add(rutaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 210, 30));

        ruta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ruta.setText("Ruta");
        bg.add(ruta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 208, 29));
        bg.add(modeloTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 208, 30));

        año_fab.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        año_fab.setText("Año de fabricacion");
        bg.add(año_fab, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 208, 32));
        bg.add(añofabTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 208, 30));

        plazas_disp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        plazas_disp.setText("Plazas disponible");
        bg.add(plazas_disp, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 208, 32));
        bg.add(plazas_dispTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, 208, 30));

        placa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        placa.setText("Placa");
        bg.add(placa, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 208, 33));
        bg.add(placaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 208, 30));

        kilome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        kilome.setText("Kilometraje");
        bg.add(kilome, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 69, -1));

        kilomeTxt.setToolTipText("");
        bg.add(kilomeTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 210, 30));

        button.setBackground(new java.awt.Color(18, 90, 173));
        button.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        button.setForeground(new java.awt.Color(255, 255, 255));
        button.setText("Registrar");
        button.setBorderPainted(false);
        button.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonActionPerformed(evt);
            }
        });
        bg.add(button, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, 214, 43));

        marcaTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marcaTxtActionPerformed(evt);
            }
        });
        bg.add(marcaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 210, 30));

        modelo1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        modelo1.setText("Modelo");
        bg.add(modelo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 208, 29));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonActionPerformed
        String kilomeString = kilomeTxt.getText();
        int klm = 0;
        String plazaString = plazas_dispTxt.getText();
        int plazas = 0;

        if (!plazaString.isEmpty() || kilomeString.isEmpty()) {
            try {
                plazas = Integer.parseInt(plazaString);
                klm = Integer.parseInt(kilomeString);// Convertimos el ID de String a int
                // Si el ID es válido, continuamos con la validación de los otros campos
            } catch (NumberFormatException e) {
                // Manejar el caso en que el ID no sea un número válido
                javax.swing.JOptionPane.showMessageDialog(this, "Los numeros deben ser enteros validos.", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                if (plazaString.isEmpty()) {
                    plazas_dispTxt.requestFocus();
                } else {
                    kilomeTxt.requestFocus();
                }
                return; // Salimos del método si el ID no es válido
            }
        } else {
            // Manejar el caso en que el ID esté vacío
            javax.swing.JOptionPane.showMessageDialog(this, "Debe ingresar un numero de plazas disponibles y un kilometraje.", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            if (plazaString.isEmpty()) {
                plazas_dispTxt.requestFocus();
            } else {
                kilomeTxt.requestFocus();
            }
            return; // Salimos del método si el ID está vacío
        }

        String marc = rutaTxt.getText();
        String model = modeloTxt.getText();
        String añofab = añofabTxt.getText();
        String plazasdisp = plazas_dispTxt.getText();
        String plac = placaTxt.getText();
        String kilom = kilomeTxt.getText();
        String rutaa = rutaTxt.getText();

        if (marc.isEmpty() || model.isEmpty() || añofab.isEmpty() || plazasdisp.isEmpty() || plac.isEmpty() || kilom.isEmpty() || rutaa.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Debe llenar todos los campos.", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            rutaTxt.requestFocus();
            return; // Salimos del método si algún campo está vacío
        }

        com.mycompany.models.Autobuses autobus = isEdition ? autobusEdition : new com.mycompany.models.Autobuses();
        autobus.setMarca(marc);
        autobus.setModelo(model);
        autobus.setAño_fabricacion(añofab);
        autobus.setPlazas_disponibles(plazas);
        autobus.setPlaca(plac);
        autobus.setKilometraje(klm);
        autobus.setRuta(rutaa);

        try {
            DAOAutobuses dao = new DAOAutobusesimpl();

            // Si se está editando, modificar el autobús existente
            if (isEdition) {
                dao.modificar(autobus);
                javax.swing.JOptionPane.showMessageDialog(this, "Autobús modificado correctamente.\n", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            } else {
                // Si no se está editando, verificar si ya existe un autobús con la misma placa
                com.mycompany.models.Autobuses existingAutobus = dao.getAutobusByPlaca(plac);
                if (existingAutobus != null) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Ya existe un autobús con esta placa.\n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
                    return; // Salir del método si ya existe un autobús con la misma placa
                } else {
                    // Si no existe un autobús con la misma placa, registrar el nuevo autobús
                    dao.registrar(autobus);
                    javax.swing.JOptionPane.showMessageDialog(this, "Autobús registrado correctamente.\n", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                }
            }

            // Limpiar los campos después del registro exitoso
            if (!isEdition) {
                rutaTxt.setText("");
                modeloTxt.setText("");
                añofabTxt.setText("");
                plazas_dispTxt.setText("");
                placaTxt.setText("");
                kilomeTxt.setText("");
                rutaTxt.setText("");
            }
        } catch (Exception e) {
            String errorMsg = isEdition ? "modificar" : "registrar";
            javax.swing.JOptionPane.showMessageDialog(this, "Ocurrió un error al " + errorMsg + " el autobús.\n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_buttonActionPerformed

    private void rutaTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rutaTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rutaTxtActionPerformed

    private void marcaTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marcaTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_marcaTxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel año_fab;
    private javax.swing.JTextField añofabTxt;
    private javax.swing.JPanel bg;
    private javax.swing.JButton button;
    private javax.swing.JLabel kilome;
    private javax.swing.JTextField kilomeTxt;
    private javax.swing.JLabel marca;
    private javax.swing.JTextField marcaTxt;
    private javax.swing.JLabel modelo1;
    private javax.swing.JTextField modeloTxt;
    private javax.swing.JLabel placa;
    private javax.swing.JTextField placaTxt;
    private javax.swing.JLabel plazas_disp;
    private javax.swing.JTextField plazas_dispTxt;
    private javax.swing.JLabel ruta;
    private javax.swing.JTextField rutaTxt;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
